application: current-time-app-lb
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest